### ISSUE TITLE
Feature Request: Latent Space Visualization 

### ISSUE THREAD

**Issue by Bariona** [zcczhang/UVD#1]
Hello Zichen, 

 Very nice work! 

 Could you release the visualization part code of the embedding space shown as follows: 

![img](https://zcczhang.github.io/UVD/assets/figs/sim_subgoals_vis.jpg)

Thank you so much! 

Quanquan Peng

**Comment by zcczhang** [comment]
Hi @Bariona, Thanks for the interest! I just pushed the code example for 2D and 3D t-SNE visualizations [here](https://github.com/zcczhang/UVD/blob/main/scripts/tsne_visualization.py). Feel free to re-open the issue if there are any further questions!
