### ISSUE TITLE
Problems when generating data

### ISSUE THREAD

**Issue by happyflying-web** [zcczhang/UVD#4]
When I use the following command to generate data，
`python datasets/data_gen.py raw_data_path="/home/dellpc/Downloads/robot/code/relay-policy-learning-master/kitchen_demos_multitask/friday_kettle_bottomknob_hinge_slide/"`
the following error occurs
`Error executing job with overrides: ['raw_data_path=/home/dellpc/Downloads/robot/code/relay-policy-learning-master/kitchen_demos_multitask/friday_kettle_bottomknob_hinge_slide/']
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/dellpc/anaconda3/envs/uvd/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/dellpc/anaconda3/envs/uvd/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/dellpc/Downloads/robot/code/UVD/datasets/data_gen.py", line 243, in generate_one_task_demo
    _generate_one_task_demo(**kwargs)
  File "/home/dellpc/Downloads/robot/code/UVD/datasets/data_gen.py", line 59, in _generate_one_task_demo
    parsed_task_name = parse_task_name(raw_task_dir)
  File "/home/dellpc/Downloads/robot/code/UVD/datasets/data_gen.py", line 20, in parse_task_name
    sub_tasks = task_name.split("-")[1].split(",")
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dellpc/Downloads/robot/code/UVD/datasets/data_gen.py", line 267, in main
    pool.map(
  File "/home/dellpc/anaconda3/envs/uvd/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/dellpc/anaconda3/envs/uvd/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.`

I find the name of file "friday_kettle_bottomknob_hinge_slide" is jointed by "_",but the code `sub_tasks = task_name.split("-")[1].split(",")` in data_gen.py is "-"

**Comment by happyflying-web** [comment]
By the way,I use this dataset https://github.com/google-research/relay-policy-learning/blob/master/kitchen_demos_multitask.zip

**Comment by happyflying-web** [comment]
The names of raw dataset's directory are as following.  I wonder if  they should be pre-processed manually. Thank you very much!
![image](https://github.com/zcczhang/UVD/assets/58216366/bca1a1fd-b43f-4352-959a-4e5550e5054d)

**Comment by zcczhang** [comment]
I'll look into this issue later but yeah probably due to the inconsistency of the filenames I used a long time ago before the release. But maybe you can just use the data I uploaded to huggingface dataset space [here](https://huggingface.co/datasets/zcczhang/UVD). :)

**Comment by happyflying-web** [comment]
I am very excited that the new dataset you provided works and the problem of filename has already solved !
But Unfortunately another error happens

> Reading configurations for Franka
> Reading configurations for Franka
> Reading configurations for Franka
> Reading configurations for Franka
> Reading configurations for Franka
> Initializing Franka sim
> Initializing Franka sim
> Initializing Franka sim
> Reading configurations for Franka
> Initializing Franka sim
> Initializing Franka sim
> Initializing Franka sim
> Reading configurations for Franka
> Reading configurations for Franka
> Reading configurations for Franka
> Reading configurations for Franka
> Reading configurations for Franka
> Reading configurations for Franka
> Initializing Franka sim
> Initializing Franka sim
> Reading configurations for Franka
> Reading configurations for Franka
> Reading configurations for Franka
> Reading configurations for Franka
> Reading configurations for Franka
> Reading configurations for Franka
> Initializing Franka sim
> Initializing Franka sim
> Initializing Franka sim
> Initializing Franka sim
> Initializing Franka sim
> Initializing Franka sim
> Initializing Franka sim
> Initializing Franka sim
> Initializing Franka sim
> Initializing Franka sim
> /home/dellpc/anaconda3/envs/uvd/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
>   logger.warn(
> kettle:   0%|                                                                                                                                           | 0/14 [00:00<?, ?it/s]Found 3 GPUs for rendering. Using device 0.
> kettle:   0%|                                                                                                                                           | 0/14 [00:00<?, ?it/s]
> Reading configurations for Franka
> Initializing Franka sim
> Reading configurations for Franka
> Initializing Franka sim
> /home/dellpc/anaconda3/envs/uvd/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
>   logger.warn(
> kettle:   0%|                                                                                                                                           | 0/24 [00:00<?, ?it/s]Found 3 GPUs for rendering. Using device 0.
> kettle:   0%|                                                                                                                                           | 0/24 [00:00<?, ?it/s]
> Reading configurations for Franka
> Initializing Franka sim
> Reading configurations for Franka
> Initializing Franka sim
> /home/dellpc/anaconda3/envs/uvd/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
>   logger.warn(
> kettle:   0%|                                                                                                                                           | 0/20 [00:00<?, ?it/s]Reading configurations for Franka
> Initializing Franka sim
> Reading configurations for Franka
> Initializing Franka sim
> /home/dellpc/anaconda3/envs/uvd/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
>   logger.warn(
> Found 3 GPUs for rendering. Using device 0.
> kettle:   0%|                                                                                                                                           | 0/22 [00:00<?, ?it/s]/home/dellpc/anaconda3/envs/uvd/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
>   logger.warn(
> kettle:   0%|                                                                                                                                           | 0/19 [00:00<?, ?it/s]Found 3 GPUs for rendering. Using device 0.
> kettle:   0%|                                                                                                                                           | 0/20 [00:00<?, ?it/s]
> Found 3 GPUs for rendering. Using device 0.
> kettle:   0%|                                                                                                                                           | 0/22 [00:00<?, ?it/s]
> kettle:   0%|                                                                                                                                           | 0/19 [00:00<?, ?it/s]
> kettle:   0%|                                                                                                                                           | 0/17 [00:00<?, ?it/s]Found 3 GPUs for rendering. Using device 0.
> kettle:   0%|                                                                                                                                           | 0/17 [00:00<?, ?it/s]
> kettle:   0%|                                                                                                                                           | 0/17 [00:00<?, ?it/s]Found 3 GPUs for rendering. Using device 0.
> kettle:   0%|                                                                                                                                           | 0/17 [00:00<?, ?it/s]
> Error executing job with overrides: []
> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/home/dellpc/anaconda3/envs/uvd/lib/python3.9/multiprocessing/pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "/home/dellpc/anaconda3/envs/uvd/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
>     return list(map(*args))
>   File "/home/dellpc/Downloads/robot/code/UVD/datasets/data_gen.py", line 243, in generate_one_task_demo
>     _generate_one_task_demo(**kwargs)
>   File "/home/dellpc/Downloads/robot/code/UVD/datasets/data_gen.py", line 70, in _generate_one_task_demo
>     env = KitchenBase(
>   File "/home/dellpc/Downloads/robot/code/UVD/uvd/envs/franka_kitchen/franka_kitchen_base.py", line 53, in __init__
>     super(KitchenBase, self).__init__(
>   File "/home/dellpc/Downloads/robot/code/UVD/uvd/envs/franka_kitchen/relay-policy-learning/adept_envs/adept_envs/utils/configurable.py", line 133, in __init__
>     base_init(self, *args, **kwargs)
>   File "/home/dellpc/Downloads/robot/code/UVD/uvd/envs/franka_kitchen/relay-policy-learning/adept_envs/adept_envs/franka/kitchen_multitask_v0.py", line 47, in __init__
>     super().__init__(
>   File "/home/dellpc/Downloads/robot/code/UVD/uvd/envs/franka_kitchen/relay-policy-learning/adept_envs/adept_envs/robot_env.py", line 79, in __init__
>     super(RobotEnv, self).__init__(
>   File "/home/dellpc/Downloads/robot/code/UVD/uvd/envs/franka_kitchen/relay-policy-learning/adept_envs/adept_envs/mujoco_env.py", line 83, in __init__
>     observation, _reward, done, _info = self.step(np.zeros(self.model.nu))
>   File "/home/dellpc/Downloads/robot/code/UVD/uvd/envs/franka_kitchen/franka_kitchen_base.py", line 314, in step
>     self.goal = self._get_task_goal()  # update goal if init
>   File "/home/dellpc/Downloads/robot/code/UVD/uvd/envs/franka_kitchen/franka_kitchen_base.py", line 123, in _get_task_goal
>     element_idx = OBS_ELEMENT_INDICES[element]
> KeyError: 'bottom_burner'
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/dellpc/Downloads/robot/code/UVD/datasets/data_gen.py", line 267, in main
>     pool.map(
>   File "/home/dellpc/anaconda3/envs/uvd/lib/python3.9/multiprocessing/pool.py", line 364, in map
>     return self._map_async(func, iterable, mapstar, chunksize).get()
>   File "/home/dellpc/anaconda3/envs/uvd/lib/python3.9/multiprocessing/pool.py", line 771, in get
>     raise self._value
> KeyError: 'bottom_burner'
> 
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by happyflying-web** [comment]
Hi~ Zichen
After my debugging, I found that the keys of the dictionary here should be "_" to connect, not spaces.
https://github.com/zcczhang/UVD/blob/51f9e7e0f8d65fffb6f9cb17faecf104e050ca49/uvd/envs/franka_kitchen/franka_kitchen_constants.py#L6C20-L6C20

**Comment by zcczhang** [comment]
Hi @ happyflying-web, after a quick check, it seems to be working on my side. Could you please double-check if the data directories are correct, e.g ` parsed_task_name = parse_task_name(raw_task_dir)` [here](https://github.com/zcczhang/UVD/blob/51f9e7e0f8d65fffb6f9cb17faecf104e050ca49/datasets/data_gen.py#L59) such that the `task_name` [here](https://github.com/zcczhang/UVD/blob/51f9e7e0f8d65fffb6f9cb17faecf104e050ca49/datasets/data_gen.py#L63) is supposed to include the space. An example of the folder in the directory is `friday_t-microwave,kettle,bottomknob,slide`. Let me know if this is not what it showed on your side!
For the place you point out [here](https://github.com/zcczhang/UVD/blob/51f9e7e0f8d65fffb6f9cb17faecf104e050ca49/uvd/envs/franka_kitchen/franka_kitchen_constants.py#L6C20-L6C20), I intentionally make it with spaces, since all variables like `FRANKA_KITCHEN_ALL_TASKS`, `OBS_ELEMENT_INDICES`, `OBS_ELEMENT_GOALS` etc [here](https://github.com/zcczhang/UVD/blob/main/uvd/envs/franka_kitchen/franka_kitchen_constants.py) all have spaces. (based on your tracebacks where the keyerror happened at `element_idx = OBS_ELEMENT_INDICES[element]`, where those elements are originally from `parsed_task_name = parse_task_name(raw_task_dir)` I mentioned earlier)

**Comment by BrightMoonStar** [comment]
The catalog of datasets downloaded at the huggingface link you provided is shown below

![image](https://github.com/zcczhang/UVD/assets/144759751/ebba0033-f751-4f91-b85c-41c5a6c9e10c)


The contents of each directory are shown below


![image](https://github.com/zcczhang/UVD/assets/144759751/06b9d4fb-5c5c-4985-a916-90be8216fffa)


I added `element=element.replace(" "," ")`  at the following two places to make the program run


![image](https://github.com/zcczhang/UVD/assets/144759751/d5f02d19-cc41-49d1-bfb6-6aa0a7586815)
![image](https://github.com/zcczhang/UVD/assets/144759751/c80c710d-ae59-4a0d-b2d5-92050ba13746)


But the generated results make me confused that only the  'kettle' directory can see the generated results,the three other directories bottom_burner,light_switch,top_burner can only see reject_sampling directory without any other files 


![image](https://github.com/zcczhang/UVD/assets/144759751/8236a209-6e91-41a4-b305-b258637b7c81)

**Comment by happyflying-web** [comment]
The catalog of datasets downloaded at the huggingface link you provided is shown below


![image](https://github.com/zcczhang/UVD/assets/58216366/2e350371-48d1-408a-9a56-7992dd714e6f)



The contents of each directory are shown below


![image](https://github.com/zcczhang/UVD/assets/58216366/10200b09-a386-4771-b1d9-010b13e136d9)



I added `element=element.replace(" "," ")` at the following two places to make the program run


![image](https://github.com/zcczhang/UVD/assets/58216366/b11d88af-b7fb-4593-a701-b6eac09add00)
![image](https://github.com/zcczhang/UVD/assets/58216366/a1210a3a-d625-4eb9-98c5-8278810e7dc4)


But the generated results only  can be seen in the 'kettle' directory ,the three other directories bottom_burner,light_switch,top_burner can only see reject_sampling directory without any other files.


![image](https://github.com/zcczhang/UVD/assets/58216366/b89e70b4-4de6-4870-8e86-4ec45ac8d268)

**Comment by happyflying-web** [comment]
Oh,excuse me, it's my fault.

**Comment by happyflying-web** [comment]
It looked very strange, and when I re-cloned the repository to run, the original problem came up again, it didn't look very stable.
```
(UVD) xxx@Precision-7920-Tower:~/Videos/bin/boot/newUVD/UVD/datasets$ python data_gen.py 
WARNING: directory (datasets/franka_kitchen_demos) already exists! 
overwrite? ([Y]/n)
Y
Deleted "datasets/franka_kitchen_demos"
Reading configurations for Franka
Reading configurations for Franka
Reading configurations for Franka
Reading configurations for Franka
Initializing Franka sim
Reading configurations for Franka
Reading configurations for Franka
Reading configurations for Franka
Initializing Franka sim
Initializing Franka sim
Reading configurations for Franka
Reading configurations for Franka
Reading configurations for Franka
Initializing Franka sim
Reading configurations for Franka
Reading configurations for Franka
Reading configurations for Franka
Initializing Franka sim
Reading configurations for Franka
Reading configurations for Franka
Reading configurations for Franka
Initializing Franka sim
Initializing Franka sim
Initializing Franka sim
Reading configurations for Franka
Reading configurations for Franka
Reading configurations for Franka
Initializing Franka sim
Reading configurations for Franka
Initializing Franka sim
Initializing Franka sim
Initializing Franka sim
Reading configurations for Franka
Initializing Franka sim
Initializing Franka sim
Initializing Franka sim
Initializing Franka sim
Initializing Franka sim
Initializing Franka sim
Initializing Franka sim
Initializing Franka sim
Reading configurations for Franka
Initializing Franka sim
Reading configurations for Franka
Initializing Franka sim
Initializing Franka sim
Reading configurations for Franka
Initializing Franka sim
/home/xxx/anaconda3/envs/UVD/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
/home/xxx/anaconda3/envs/UVD/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
/home/xxx/anaconda3/envs/UVD/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
kettle:   0%|                                                                                                                                                | 0/17 [00:00<?, ?it/s]/home/xxx/anaconda3/envs/UVD/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
/home/xxx/anaconda3/envs/UVD/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
/home/xxx/anaconda3/envs/UVD/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
/home/xxx/anaconda3/envs/UVD/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
kettle:   0%|                                                                                                                                                | 0/20 [00:00<?, ?it/s]Found 1 GPUs for rendering. Using device 0.
Found 1 GPUs for rendering. Using device 0.
Found 1 GPUs for rendering. Using device 0.
Found 1 GPUs for rendering. Using device 0.
Found 1 GPUs for rendering. Using device 0.
Found 1 GPUs for rendering. Using device 0.
Found 1 GPUs for rendering. Using device 0.
100%|??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 193/193 [00:20<00:00,  9.39it/s]
kettle:   0%|                                                                                                                                                | 0/19 [00:24<?, ?it/s]
100%|??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 204/204 [00:21<00:00,  9.46it/s]
100%|??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 207/207 [00:22<00:00,  9.35it/s]
kettle:   0%|                                                                                                                                                | 0/17 [00:25<?, ?it/s]
kettle:   0%|                                                                                                                                                | 0/22 [00:25<?, ?it/s]
100%|??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 225/225 [00:22<00:00,  9.83it/s]
kettle:   0%|                                                                                                                                                | 0/14 [00:26<?, ?it/s]
100%|??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 230/230 [00:23<00:00,  9.88it/s]
kettle:   0%|                                                                                                                                                | 0/24 [00:26<?, ?it/s]
100%|??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 241/241 [00:23<00:00, 10.22it/s]
kettle:   0%|                                                                                                                                                | 0/20 [00:27<?, ?it/s]
100%|??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 253/253 [00:23<00:00, 10.61it/s]
kettle:   0%|                                                                                                                                                | 0/17 [00:27<?, ?it/s]
Error executing job with overrides: []
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/UVD/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/xxx/anaconda3/envs/UVD/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/xxx/Videos/bin/boot/newUVD/UVD/datasets/data_gen.py", line 243, in generate_one_task_demo
    _generate_one_task_demo(**kwargs)
  File "/home/xxx/Videos/bin/boot/newUVD/UVD/datasets/data_gen.py", line 70, in _generate_one_task_demo
    env = KitchenBase(
  File "/home/xxx/Videos/bin/boot/UVD/uvd/envs/franka_kitchen/franka_kitchen_base.py", line 53, in __init__
    super(KitchenBase, self).__init__(
  File "/home/xxx/Videos/bin/boot/UVD/uvd/envs/franka_kitchen/relay-policy-learning/adept_envs/adept_envs/utils/configurable.py", line 133, in __init__
    base_init(self, *args, **kwargs)
  File "/home/xxx/Videos/bin/boot/UVD/uvd/envs/franka_kitchen/relay-policy-learning/adept_envs/adept_envs/franka/kitchen_multitask_v0.py", line 47, in __init__
    super().__init__(
  File "/home/xxx/Videos/bin/boot/UVD/uvd/envs/franka_kitchen/relay-policy-learning/adept_envs/adept_envs/robot_env.py", line 79, in __init__
    super(RobotEnv, self).__init__(
  File "/home/xxx/Videos/bin/boot/UVD/uvd/envs/franka_kitchen/relay-policy-learning/adept_envs/adept_envs/mujoco_env.py", line 83, in __init__
    observation, _reward, done, _info = self.step(np.zeros(self.model.nu))
  File "/home/xxx/Videos/bin/boot/UVD/uvd/envs/franka_kitchen/franka_kitchen_base.py", line 314, in step
    self.goal = self._get_task_goal()  # update goal if init
  File "/home/xxx/Videos/bin/boot/UVD/uvd/envs/franka_kitchen/franka_kitchen_base.py", line 123, in _get_task_goal
    element_idx = OBS_ELEMENT_INDICES[element]
KeyError: 'light_switch'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xxx/Videos/bin/boot/newUVD/UVD/datasets/data_gen.py", line 267, in main
    pool.map(
  File "/home/xxx/anaconda3/envs/UVD/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/xxx/anaconda3/envs/UVD/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: 'light_switch'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by zcczhang** [comment]
I just grabbed a new machine and set up everything from scratch, everything works well. Maybe also recreate the conda env?

**Comment by zcczhang** [comment]
> The names of raw dataset's directory are as following. I wonder if they should be pre-processed manually. Thank you very much! ![image](https://private-user-images.githubusercontent.com/58216366/285868077-bca1a1fd-b43f-4352-959a-4e5550e5054d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNTQ1NzEsIm5iZiI6MTcwNzM1NDI3MSwicGF0aCI6Ii81ODIxNjM2Ni8yODU4NjgwNzctYmNhMWExZmQtYjQzZi00MzUyLTk1OWEtNGU1NTUwZTUwNTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDAxMDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NjVkY2E4N2ViNDZiODRhYmU3ZDdhN2E0OTExMDU5NDMwNGNjNTUxZDgyYWE2MmQzZTE3NWViYjRhMjFkNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5ir-fdsLFNtGGvvVfDY8G6wJG_6M6ZkGQqiZA9QaMVI)

btw after checking the thread above, the `raw_data_path` should be pointed to this folder, ie containing all long-horizon tasks, sth like `datasets/franka_kitchen_raw_dataset/full`

**Comment by capediemmmm** [comment]
Hello there. I've been faced with the same problem. I use the dataset [here](https://huggingface.co/datasets/zcczhang/UVD). The folder in the directory is not `friday_t-microwave,kettle,bottomknob,slide` but the form like `bottom_burner-top_burner-light_switch-slide_cabinet`. How did you solve this problem?

````
Traceback (most recent call last):
  File "/home/disk3/xxx/UVD/./datasets/data_gen.py", line 307, in main
    _generate_one_task_demo(
  File "/home/disk3/xxx/UVD/./datasets/data_gen.py", line 108, in _generate_one_task_demo
    obs = env.reset(task_elements=task_elements, seed=seed)
  File "/home/disk3/xxx/UVD/datasets/../uvd/envs/franka_kitchen/franka_kitchen_base.py", line 150, in reset
    super().reset()
  File "/home/disk3/xxx/UVD/datasets/../uvd/envs/franka_kitchen/relay-policy-learning/adept_envs/adept_envs/mujoco_env.py", line 144, in reset
    return self._reset()
  File "/home/disk3/xxx/UVD/datasets/../uvd/envs/franka_kitchen/relay-policy-learning/adept_envs/adept_envs/mujoco_env.py", line 149, in _reset
    ob = self.reset_model()
  File "/home/disk3/xxx/UVD/datasets/../uvd/envs/franka_kitchen/relay-policy-learning/adept_envs/adept_envs/franka/kitchen_multitask_v0.py", line 167, in reset_model
    self.goal = self._get_task_goal()  # sample a new goal on reset
  File "/home/disk3/xxx/UVD/datasets/../uvd/envs/franka_kitchen/franka_kitchen_base.py", line 123, in _get_task_goal
    element_idx = OBS_ELEMENT_INDICES[element]
KeyError: 'light_switch'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
````
