### ISSUE TITLE
problems about real-world-data

### ISSUE THREAD

**Issue by happyflying-web** [zcczhang/UVD#5]
Hi~
After downloading the real-world-data from https://huggingface.co/datasets/zcczhang/UVD/tree/main/real-world-data , I find a lot of picture files are corrupted,and the size of the files are shown 0 bytes as following screenshot.
![image](https://github.com/zcczhang/UVD/assets/58216366/ebaa6bfe-ec92-4ac2-984b-33b231cc4354)

**Comment by happyflying-web** [comment]
Corrupted files mostly occur in Apple-in-Oven，and through comparison, I find that the file size of Apple-in-Oven is much smaller than the other two.

![image](https://github.com/zcczhang/UVD/assets/58216366/7dcb19e1-2977-4b77-a6c2-b204b9a084dd)

**Comment by zcczhang** [comment]
Ah, good catch! Thanks for pointing this out and I'll get back to you when I update the data.

**Comment by zcczhang** [comment]
Sorry forgot to upload for a long time and now it should be the same as what we used in the paper: https://huggingface.co/datasets/zcczhang/UVD/tree/main/real-world-data
